name: auto deploy

on: [push]

jobs:
  build:

    runs-on: [self-hosted, linux]

    steps:
    - uses: actions/checkout@v1
    - name: yarn install
      run:
        yarn
        
    - name: remove bin
      run:
        rm -rf bin

    - name: typescript compile
      run: npx tsc
    
    - name: run process with pm2
      run: |
        pm2 stop 0
        pm2 delete 0
        pm2 start bin/app.js
